version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tortoise-orm
    versions:
    - 0.16.21
    - 0.17.0
    - 0.17.1
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: environs
    versions:
    - 9.3.0
    - 9.3.1
  - dependency-name: orjson
    versions:
    - 3.4.8
    - 3.5.0
  - dependency-name: asyncpg
    versions:
    - 0.21.0
