version: "2"
run:
  go: "1.24"
  relative-path-mode: gomod
  issues-exit-code: 2
  tests: true
  allow-parallel-runners: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gosec
    - importas
    - intrange
    - ireturn
    - loggercheck
    - mirror
    - misspell
    - mnd
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      check:
        - switch
        - map
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - mnd
        source: \* ?time\.
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
