-- Write your migrate up statements here
create table show
(
    show_id          bigint generated by default as identity primary key,
    -- display name of the show
    name             text        not null,
    -- short-name of the show used in URLs
    slug             text        not null,
    -- date the show started airing
    first_aired      timestamptz not null,
    -- date the show stopped airing if it is no longer running
    last_aired       timestamptz,

    -- These values are for the UI
    -- primary_colour stores the hex colour value associated with the show
    primary_colour   text        not null
        constraint only_hex_primary_colour check (primary_colour ~* '^#[a-f0-9]{6}$'),
    secondary_colour text        not null
        constraint only_hex_secondary_colour check (primary_colour ~* '^#[a-f0-9]{6}$'),
    accent_colour    text        not null
        constraint only_hex_accent_colour check (primary_colour ~* '^#[a-f0-9]{6}$'),

    created_at       timestamptz not null default now(),
    modified_at      timestamptz not null default now()
);

create table episode
(
    episode_id  bigint generated by default as identity primary key,
    -- display name of the episode
    name        text          not null,
    -- date the episode first aired
    air_date    timestamptz   not null,
    -- season this episode is from
    season      smallint      not null
        constraint only_positive_seasons check ( season > 0 ),
    -- number of the episode in the season
    episode     smallint      not null
        constraint only_positive_episodes check ( episode > 0 ),
    -- brief description of the episode. Expect that the reason can be empty, but we do not want nulls
    description text          not null,
    -- https link to the source of additional information
    source_link text          not null
        constraint only_https_source_links check ( source_link ilike 'https://%' ),

    -- ordering column that determines where in the list the episode is shown
    ordering    integer       not null
        constraint only_positive_ordering check ( ordering > 0 ),
    -- foreign key reference to the show this episode is from
    show_id     bigint unique not null references show (show_id),

    created_at  timestamptz   not null default now(),
    modified_at timestamptz   not null default now(),

    constraint only_unique_episode_number_per_season unique (season, episode)
);

create index idx_episode_show_id_fk on episode (show_id);

---- create above / drop below ----

drop index idx_episode_show_id_fk;
drop table episode cascade;
drop table show cascade;
