WIKIPEDIA = 'wikipedia'

ARROW = 'ARROW'
CONSTANTINE = 'CONSTANTINE'
FLASH = 'THE FLASH'
FREEDOM_FIGHTERS = 'FREEDOM FIGHTERS: THE RAY'
LEGENDS_OF_TOMORROW = "DC'S LEGENDS OF TOMORROW"
SUPERGIRL = 'SUPERGIRL'
VIXEN = 'VIXEN'
