// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_full_episode_list.sql

package db

import (
	"context"
	"time"
)

const getEpisodes = `-- name: GetEpisodes :many
select show.name as show_name,
       show.slug as show_slug,
       ep.episode_id,
       ep.name,
       ep.air_date,
       ep.season,
       ep.episode,
       ep.description,
       ep.source_link,
       ep.ordering,
       ep.show_id,
       ep.created_at,
       ep.modified_at,
       ep.runtime_minutes
from episode as ep
         inner join show on show.show_id = ep.show_id
order by ordering
`

type GetEpisodesRow struct {
	AirDate        time.Time
	CreatedAt      time.Time
	ModifiedAt     time.Time
	ShowName       string
	ShowSlug       string
	Name           string
	Description    string
	SourceLink     string
	EpisodeID      int64
	ShowID         int64
	Ordering       int32
	Season         int16
	Episode        int16
	RuntimeMinutes int16
}

func (q *Queries) GetEpisodes(ctx context.Context) ([]GetEpisodesRow, error) {
	rows, err := q.db.Query(ctx, getEpisodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodesRow
	for rows.Next() {
		var i GetEpisodesRow
		if err := rows.Scan(
			&i.ShowName,
			&i.ShowSlug,
			&i.EpisodeID,
			&i.Name,
			&i.AirDate,
			&i.Season,
			&i.Episode,
			&i.Description,
			&i.SourceLink,
			&i.Ordering,
			&i.ShowID,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RuntimeMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
