// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_show_list.sql

package db

import (
	"context"
)

const getShowList = `-- name: GetShowList :many
select slug,
       name,
       data_sources
from show
order by show_id
`

type GetShowListRow struct {
	Slug        string
	Name        string
	DataSources []string
}

func (q *Queries) GetShowList(ctx context.Context) ([]GetShowListRow, error) {
	rows, err := q.db.Query(ctx, getShowList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetShowListRow
	for rows.Next() {
		var i GetShowListRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.DataSources); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
