// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	GetEpisodes(ctx context.Context) ([]GetEpisodesRow, error)
	GetEpisodesFiltered(ctx context.Context, hideShowSlugs []string, fromDate *time.Time, toDate *time.Time) ([]GetEpisodesRow, error)
	GetShowList(ctx context.Context) ([]GetShowListRow, error)
}

var _ Querier = (*Queries)(nil)
