// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetEpisodes(ctx context.Context) ([]GetEpisodesRow, error)
	GetShowList(ctx context.Context) ([]GetShowListRow, error)
}

var _ Querier = (*Queries)(nil)
